package com.tinet.dao;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of 业务数据表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class TestDataMainTest implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 编号. */
	private String id;

	/** 归属用户. */
	private String userId;

	/** 归属部门. */
	private String officeId;

	/** 归属区域. */
	private String areaId;

	/** 名称. */
	private String name;

	/** 性别. */
	private String sex;

	/** 加入日期. */
	private Date inDate;

	/** 创建者. */
	private String createBy;

	/** 创建时间. */
	private Date createDate;

	/** 更新者. */
	private String updateBy;

	/** 更新时间. */
	private Date updateDate;

	/** 备注信息. */
	private String remarks;

	/** 删除标记. */
	private String delFlag;

	/** The set of 业务数据子表. */
	private Set<TestDataChildTest> testDataChildSet;

	/**
	 * Constructor.
	 */
	public TestDataMainTest() {
		this.testDataChildSet = new HashSet<TestDataChildTest>();
	}

	/**
	 * Set the 编号.
	 * 
	 * @param id
	 *            编号
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * Get the 编号.
	 * 
	 * @return 编号
	 */
	public String getId() {
		return this.id;
	}

	/**
	 * Set the 归属用户.
	 * 
	 * @param userId
	 *            归属用户
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * Get the 归属用户.
	 * 
	 * @return 归属用户
	 */
	public String getUserId() {
		return this.userId;
	}

	/**
	 * Set the 归属部门.
	 * 
	 * @param officeId
	 *            归属部门
	 */
	public void setOfficeId(String officeId) {
		this.officeId = officeId;
	}

	/**
	 * Get the 归属部门.
	 * 
	 * @return 归属部门
	 */
	public String getOfficeId() {
		return this.officeId;
	}

	/**
	 * Set the 归属区域.
	 * 
	 * @param areaId
	 *            归属区域
	 */
	public void setAreaId(String areaId) {
		this.areaId = areaId;
	}

	/**
	 * Get the 归属区域.
	 * 
	 * @return 归属区域
	 */
	public String getAreaId() {
		return this.areaId;
	}

	/**
	 * Set the 名称.
	 * 
	 * @param name
	 *            名称
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Get the 名称.
	 * 
	 * @return 名称
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * Set the 性别.
	 * 
	 * @param sex
	 *            性别
	 */
	public void setSex(String sex) {
		this.sex = sex;
	}

	/**
	 * Get the 性别.
	 * 
	 * @return 性别
	 */
	public String getSex() {
		return this.sex;
	}

	/**
	 * Set the 加入日期.
	 * 
	 * @param inDate
	 *            加入日期
	 */
	public void setInDate(Date inDate) {
		this.inDate = inDate;
	}

	/**
	 * Get the 加入日期.
	 * 
	 * @return 加入日期
	 */
	public Date getInDate() {
		return this.inDate;
	}

	/**
	 * Set the 创建者.
	 * 
	 * @param createBy
	 *            创建者
	 */
	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	/**
	 * Get the 创建者.
	 * 
	 * @return 创建者
	 */
	public String getCreateBy() {
		return this.createBy;
	}

	/**
	 * Set the 创建时间.
	 * 
	 * @param createDate
	 *            创建时间
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * Get the 创建时间.
	 * 
	 * @return 创建时间
	 */
	public Date getCreateDate() {
		return this.createDate;
	}

	/**
	 * Set the 更新者.
	 * 
	 * @param updateBy
	 *            更新者
	 */
	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	/**
	 * Get the 更新者.
	 * 
	 * @return 更新者
	 */
	public String getUpdateBy() {
		return this.updateBy;
	}

	/**
	 * Set the 更新时间.
	 * 
	 * @param updateDate
	 *            更新时间
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * Get the 更新时间.
	 * 
	 * @return 更新时间
	 */
	public Date getUpdateDate() {
		return this.updateDate;
	}

	/**
	 * Set the 备注信息.
	 * 
	 * @param remarks
	 *            备注信息
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	/**
	 * Get the 备注信息.
	 * 
	 * @return 备注信息
	 */
	public String getRemarks() {
		return this.remarks;
	}

	/**
	 * Set the 删除标记.
	 * 
	 * @param delFlag
	 *            删除标记
	 */
	public void setDelFlag(String delFlag) {
		this.delFlag = delFlag;
	}

	/**
	 * Get the 删除标记.
	 * 
	 * @return 删除标记
	 */
	public String getDelFlag() {
		return this.delFlag;
	}

	/**
	 * Set the set of the 业务数据子表.
	 * 
	 * @param testDataChildSet
	 *            The set of 业务数据子表
	 */
	public void setTestDataChildSet(Set<TestDataChildTest> testDataChildSet) {
		this.testDataChildSet = testDataChildSet;
	}

	/**
	 * Add the 业务数据子表.
	 * 
	 * @param testDataChild
	 *            业务数据子表
	 */
	public void addTestDataChild(TestDataChildTest testDataChild) {
		this.testDataChildSet.add(testDataChild);
	}

	/**
	 * Get the set of the 业务数据子表.
	 * 
	 * @return The set of 业务数据子表
	 */
	public Set<TestDataChildTest> getTestDataChildSet() {
		return this.testDataChildSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		TestDataMainTest other = (TestDataMainTest) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
